# Generated by Django 5.2.4 on 2025-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_event_item_itemevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Events',
            field=models.ManyToManyField(blank=True, related_name='users', to='Main.event'),
        ),
    ]
